Feature/components info
krzysztoffila/documentation-vue pull request #5
Opened 2023-02-25 14:50 UTC by krzysztoffila

Zmiana klasy w divach.

2023-02-26 10:08 UTC, krzysztoffila commented
Chyba coś mi się pomyliło z pull requestem. Ogólnie chce zmiany w ikonach zrobić na v-if i jak daje warunki to się nie wyświetlają....

2023-02-26 11:24 UTC, your-brain404 approved these changes

2023-02-26 11:28 UTC, your-brain404 requested changes

2023-02-26 11:28 UTC, your-brain404 commented on src/components/page-elements/info.vue
> +        v-if="type == info"
Nie rób tego na v-if. Nalezy zbindowac atrybut "icon" i przekazac nazwę ikony w zależności od propsa type. Węzeł <b-icon> ma być tylko jeden.

2023-02-27 14:30 UTC, your-brain404 requested changes

2023-02-27 14:30 UTC, your-brain404 commented on src/components/page-elements/info.vue
> +      <svg
Svg ma być załadowane z tagu img 😅 stwórz plik info.svg i wrzuć tam kod svg ikony

2023-02-27 14:30 UTC, your-brain404 commented on src/components/page-elements/info.vue
> +      <b-icon :class="info" :icon="icons[type]" :variant="type"></b-icon>
W przypadku wrzucenia svg poprzez img - b-icon wywalimy

2023-02-27 17:08 UTC, your-brain404 approved these changes
Chciałem, żeby ikona była jako img ale niech już będzie XD

2023-02-27 17:08 UTC, merged