Dodano folder z ikonami bootstrap
krzysztoffila/documentation-vue pull request #6
Opened 2023-02-28 09:35 UTC by krzysztoffila

W końcu znalazłem ikony!

2023-02-28 17:22 UTC, your-brain404 requested changes
Chyba zwariowałeś, że dałeś tu wszystkie ikony XD usuń niepotrzebne

2023-03-04 16:13 UTC, your-brain404 requested changes

2023-03-04 16:13 UTC, your-brain404 commented on src/App.vue
> +  display: flex !important;
Important już jest zbędny jeśli bootstrap jest na samej gorze

2023-03-04 16:13 UTC, your-brain404 commented on src/components/page-elements/info.vue
>    <div :class="['info', type && `info--${type}`]" class="info__container">
Odkąd type jest defaultowo info, wystarczy zapis 'info--${type}' bez type &&. Nie potrzebujemy już sprawdzać czy jest ustawione bo zawsze będzie.

2023-03-04 20:30 UTC, krzysztoffila commented on src/components/page-elements/info.vue
>    <div :class="['info', type && `info--${type}`]" class="info__container">
Dobra!

2023-03-04 21:09 UTC, merged